apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-root
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp-root
          image: jasmeetsingh94/ingress-app:1.0
          ports:
            - containerPort: 80
   