apiVersion: v1
kind: Service
metadata:
  name: network-lb-svc
  annotations:
    # Name of the load balancer
     alb.ingress.kubernetes.io/load-balancer-name: test-nlb-ingress-host
     # type of load balancer
     alb.ingress.kubernetes.io/scheme: internet-facing
     service.beta.kubernetes.io/aws-load-balancer-type: external
     # Healthchecks
     alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
     alb.ingress.kubernetes.io/healthcheck-port: traffic-port
     service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /index.html
     alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
     alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
     alb.ingress.kubernetes.io/success-codes: '200'
     alb.ingress.kubernetes.io/healthy-threshold-count: '2'
     alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
     # SSL Settings
     #alb.ingress.kubernetes.io/certificate-arn:  Ingress will automatically discover certificate related to hosted zone 
     alb.ingress.kubernetes.io/aws-load-balancer-ssl-ports: '443'
     # External Dns Settings
     external-dns.alpha.kubernetes.io/hostname: nlb.jasmeetdevops.com
     # Access Control
     service.beta.kubernetes.io/load-balancer-source-ranges: 0.0.0.0/0  # specifies the CIDRs that are allowed to access the NLB.
     service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # specifies whether the NLB will be internet-facing or internal 
     # AWS Resource Tags
     service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=dev,Team=devops
     service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp 

     
spec:
  selector:
    app: myapp1
  ports:
  - port: 80
    targetPort: 80
  
  - port: 443
    targetPort: 443
