apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-clusterautoscaler
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: jasmeetsingh94/alb-ingress
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80





---
apiVersion: v1
kind: Service
metadata:
  name: cluster-autoscaler-svc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
    
